# Generated by Django 5.1.3 on 2024-11-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_projects_alter_user_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='correo',
            field=models.CharField(max_length=200),
        ),
    ]
