# Generated by Django 5.1.3 on 2024-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0004_remove_user_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(related_name='users', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='correo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
